### ISSUE TITLE
Issues with "variable" tile size (collection.barnesfoundation.org)

### ISSUE THREAD

**Issue by yjml** [lovasoa/dezoomify-rs#114]
I'm able to create partial stitchs of the images from  
https://collection.barnesfoundation.org/  
e.g. https://collection.barnesfoundation.org/objects/6312/Two-Women-by-the-Shore-Mediterranean/ using the following yaml:

```yaml
url_template: "https://d2r83x5xt28klo.cloudfront.net/tiles/6312/{{x}},{{y}},256,256/256,/0/color.jpg"
variables:
  - { name: x, from: 0, to: 6656, step: 256 }
  - { name: y, from: 0, to: 4608, step: 256 }
headers:
  referer: "https://collection.barnesfoundation.org/objects/6312/Two-Women-by-the-Shore-Mediterranean/"
```

However, as noted, these are partial images because apparently the bottom and right side tiles (and their URLs) are sized differently (in the example case, the lower right corner would be 232x239 with URL https://d2r83x5xt28klo.cloudfront.net/tiles/6312/6656,4608,232,239/232,/0/color.jpg )
