### ISSUE TITLE
Topographical maps from Tōhoku University Library

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-rs#13]
I wanted to ask if **dezoomify-rs** provides the possibility to dezoomify great topographical maps uploaded with [this system](http://chiri.es.tohoku.ac.jp/~gaihozu/ghz-dtl.php?lang=ja-JP&fm=l&ghzno=OC016903) (that I don't know). For example, the map quoted above can be found zoomable [here](http://chiri.es.tohoku.ac.jp/~gaihozu/viewer/index.php?ghzno=OC016903).

**Comment by lovasoa** [comment]
I managed to get it working using the custom yaml dezoomer with the following `tiles.yaml`:

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "http://chiri.es.tohoku.ac.jp/~gaihozu/map/xl/OC016903/tile_000_{{x/256/100%10}}{{x/256/10%10}}{{x/256%10}}_{{y/256/100%10}}{{y/256/10%10}}{{y/256%10}}.jpg"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 6912 # Image width
    step: 256

  - name: y
    from: 0
    to: 5632 # Image height
    step: 256
```

I understand that this format (the url_template in particular) is hard to read and to write. Maybe we should thing about a better way to define a custom tile scheme...
