### ISSUE TITLE
Google Earth and the Museo del Prado

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#55]
Hello,
A few years ago, the Museo del Prado "partnered" with Google to have 14 Works of Art in high definition on its Google Earth platform.
Later all traces of the mosaics disappeared.
Reviewing my hard drives I have found the possibility to download these works. An example:

http://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/P02179/img/img_7_74_93.jpg

http://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/P02179/img/img_1_0_0.jpg

It is the self-portrait of Albert Dürer "Wonderful"

It is true that there is a project on Wikipedia that has deposited the works to a very good definition; but...

Trying to apply a standard template with its wonderful program:

dezoomify-rs http://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/P02179/img/img_2_{{X}}_{{(Y)}}.jpg 001.png

I have found that Y's do not follow incremental logic. I think the X's do.

I understand that a tiles.yaml should be applied; but....

I am very lost, the truth.

Thanks for everything and greetings,

**Comment by lovasoa** [comment]
Here is a tiles.yaml to use : 

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "http://mw2.google.com/mw-earth-vectordb/gallery_layers/prado/P02179/img/img_7_{{x/tilesize}}_{{93-y/tilesize}}.jpg"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 18944 # Image width = 74 * 256
    step: 256 # Tile width

  - name: y
    from: 0
    to: 23808 # Image height
    step: 256 # Tile height

  - name: tilesize
    value: 256
```

It computes the y position of tiles with the formula `93 - y/tilesize`
You should be able to easily adapt that to other images.
I strongly encourage you to [upload the other artworks to wikimedia](https://commons.wikimedia.org/wiki/Special:UploadWizard) so that they are never lost again.

I uploaded the durer here: https://commons.wikimedia.org/wiki/File:Self-portrait_of_Albert_D%C3%BCrer.jpg
