### ISSUE TITLE
Map server returns PNG encoding error

### ISSUE THREAD

**Issue by lost-geographer** [lovasoa/dezoomify-rs#61]
Hello everybody,

I am trying to download a topographical map accessible from here : http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/#apuane_25k_2018_288dpi/ol3. I thought that something simple like this would work :

`dezoomify-rs -r 0 http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/16/{{X}}/{{Y}}.png`

Or something more complex like this (following the example shown [here](https://github.com/lovasoa/dezoomify/issues/380#issuecomment-612965275)) :

`dezoomify-rs --retries 0 "http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/wmt/wmts?&crs=EPSG:3857&dpiMode=7&format=image/png&layers=apuane_25k_2018_288dpi&styles=default&tileMatrixSet=GoogleMapsCompatible&tilematrix=16&tilerow={{X}}&tilecol={{Y}}"`

But in each case I got this error : `ERROR PNG encoding error: Zero width not allowed`.

Do you have any idea ?

**Comment by lovasoa** [comment]
It looks like your URL template doesnt lead to valid image links, at least for x=0 and y=0 : 

http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/16/0/0.png

**Comment by lovasoa** [comment]
Once you figure out which are the min and max allowed values for x and y, you can use the [custom yaml dezoomer](https://github.com/lovasoa/dezoomify-rs#Custom-yaml)

**Comment by lovasoa** [comment]
I am going to close this specific issue, and create a new one concerning the support of WMTS images in dezoomify-rs. Supporting WMTS would give full support for this image.

**Comment by lost-geographer** [comment]
For the record : I did it ! Using the following command `dezoomify-rs -r 0 tiles.yaml result.jpg` and the YAML parameters below :

```
url_template: "http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/16/{{34587+x/256}}/{{23783+y/256}}.png"

# Each tile size is 256

# X/Y URL values at corners
# Top Right - Left   : 34587/23783 - 34682/23783
# Bottom Right - Left: 34587/23849 - 34682/23849

# Values start at the top right corner and finish at the bottom left one.
# X starts at 34587
# Y starts at 23783

# X URL value changes of 1 unit horizontally, so we have 34682−34587 = 95 tiles. The image width is 95x256 = 24320

# Y URL value changes of 1 unit vertically, so we have 23849−23783 = 66 tiles vertically. The image height : 66x256 = 16896

variables:
  - name: x
    from: 0   # Always from 0
    to: 24320 # Image width
    step: 256 # Tile width

  - name: y
    from: 0   # Always from 0
    to: 16896 # Image height
    step: 256 # Tile height
```
