### ISSUE TITLE
Feature request: new dezoomer for WMTS maps

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-rs#62]
[WMTS](https://www.ogc.org/standards/wmts) is a standard format for storing 2D map tiles. If dezoomify-rs could implement (a subset of) the specification, it would allow downloading high-resolution maps from many different sources.

See #61

**Comment by lovasoa** [comment]
Here is an example of a WMTS meta-information url: http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/wmt/wmts?&crs=EPSG:3857&dpiMode=7&format=image/png&layers=apuane_25k_2018_288dpi


and an excerpt of the contents : 

```xml
<Capabilities xsi:schemaLocation="http://www.opengis.net/wmts/1.0 http://schemas.opengis.net/wmts/1.0/wmtsGetCapabilities_response.xsd" version="1.0.0">
<!-- Service Identification -->
<ows:ServiceIdentification>
<ows:Title>tileserverphp</ows:Title>
<ows:ServiceType>OGC WMTS</ows:ServiceType>
<ows:ServiceTypeVersion>1.0.0</ows:ServiceTypeVersion>
</ows:ServiceIdentification>
<!-- Operations Metadata -->
<ows:OperationsMetadata>
</ows:OperationsMetadata>
<Contents>
<Layer>
</Layer>
<Layer>
</Layer>
<Layer>
</Layer>
<Layer>
</Layer>
<Layer>
</Layer>
<Layer>
</Layer>
<Layer>
</Layer>
<Layer>
<ows:Title>TRENTINO</ows:Title>
<ows:Identifier>trentino</ows:Identifier>
<ows:WGS84BoundingBox crs="urn:ogc:def:crs:OGC:2:84">
<ows:LowerCorner>10.44 45.66</ows:LowerCorner>
<ows:UpperCorner>11.98 46.55</ows:UpperCorner>
</ows:WGS84BoundingBox>
<Style isDefault="true">
<ows:Identifier>default</ows:Identifier>
</Style>
<Format>image/png</Format>
<TileMatrixSetLink>
<TileMatrixSet>GoogleMapsCompatible</TileMatrixSet>
</TileMatrixSetLink>
<ResourceURL format="image/png" resourceType="tile" template="http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/wmt/trentino/{TileMatrix}/{TileCol}/{TileRow}.png"/>
</Layer>
<TileMatrixSet>
<ows:Title>GoogleMapsCompatible</ows:Title>
<ows:Abstract>GoogleMapsCompatible EPSG:3857</ows:Abstract>
<ows:Identifier>GoogleMapsCompatible</ows:Identifier>
<ows:SupportedCRS>urn:ogc:def:crs:EPSG::3857</ows:SupportedCRS>
<TileMatrix>
<ows:Identifier>0</ows:Identifier>
<ScaleDenominator>559082264.02872</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>256</TileWidth>
<TileHeight>256</TileHeight>
<MatrixWidth>1</MatrixWidth>
<MatrixHeight>1</MatrixHeight>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
<ows:Identifier>13</ows:Identifier>
<ScaleDenominator>68247.346683193</ScaleDenominator>
<TopLeftCorner>-20037508.34 20037508.34</TopLeftCorner>
<TileWidth>256</TileWidth>
<TileHeight>256</TileHeight>
<MatrixWidth>8192</MatrixWidth>
<MatrixHeight>8192</MatrixHeight>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
<TileMatrix>
</TileMatrix>
</TileMatrixSet>
<TileMatrixSet>
</TileMatrixSet>
</Contents>
<ServiceMetadataURL xlink:href="http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/wmt/wmts/1.0.0/WMTSCapabilities.xml"/>
</Capabilities>
```

**Comment by lost-geographer** [comment]
I dit it ! With the following command `dezoomify-rs -r 0 tiles.yaml result.jpg` and YAML parameters :

```
url_template: "http://tiles.webmapp.it/apuane_25k_2018_288dpi/apuane_25k_2018_288dpi/16/{{34587+x/256}}/{{23783+y/256}}.png"

# Each tile size is 256

# X/Y URL values at corners
# Top Right - Left   : 34587/23783 - 34682/23783
# Bottom Right - Left: 34587/23849 - 34682/23849

# Values start at the top right corner and finish at the bottom left one.
# X starts at 34587
# Y starts at 23783

# X URL value changes of 1 unit horizontally, so we have 34682−34587 = 95 tiles. The image width is 95x256 = 24320

# Y URL value changes of 1 unit vertically, so we have 23849−23783 = 66 tiles vertically. The image height : 66x256 = 16896

variables:
  - name: x
    from: 0   # Always from 0
    to: 24320 # Image width
    step: 256 # Tile width

  - name: y
    from: 0   # Always from 0
    to: 16896 # Image height
    step: 256 # Tile height
```
