### ISSUE TITLE
Palace Museum website blocked

### ISSUE THREAD

**Issue by tojoshuazhang** [lovasoa/dezoomify-rs#65]
I used to be able to construct yaml file to download images from this Palace Museum website: https://minghuaji.dpm.org.cn/paint/list/, but it seems the website now blocks the usage of dezoomify-rs. I was still able to find the tiles URL & size of the image to construct the yaml file, but when running dezoomify-rs it returns error message. So just want to confirm it's indeed the website that block this app or sth else. Thank you!

using this page as example: https://minghuaji.dpm.org.cn/paint/appreciate?id=a1fe5299f5834bb188885795985aa743 

I constructed this yaml:

```yaml
url_template: "https://minghuaji-1259446244.cos.ap-beijing.myqcloud.com/bundle/dbd60efc668b47aa870f58fe16b9c81a//13/{{x/254}}_{{y/254}}.png"

variables:
  - name: x
    from: 0
    to: 4801 # Image width, taken from stage 1
    step: 254 # Tile width, taken from stage 1

  - name: y
    from: 0
    to: 8128 # Image height
    step: 254 # Tile height
```

**Comment by lovasoa** [comment]
Hello,
  Their servers refuse to serve tiles when the [HTTP Referer header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) is not set to the domain of their official image viewer. You can easily work around that by setting the HTTP headers you want to send from your `tiles.yaml` file : 

```yaml
url_template: "https://minghuaji-1259446244.cos.ap-beijing.myqcloud.com/bundle/dbd60efc668b47aa870f58fe16b9c81a//13/{{x/254}}_{{y/254}}.png"

variables:
  - name: x
    from: 0
    to: 4801 # Image width, taken from stage 1
    step: 254 # Tile width, taken from stage 1

  - name: y
    from: 0
    to: 8128 # Image height
    step: 254 # Tile height

headers:
  Referer: "https://minghuaji.dpm.org.cn/"
```


![ming_lowqual](https://user-images.githubusercontent.com/552629/90409555-9c9f4580-e0a9-11ea-9fac-29862a647e9a.jpg)
